In [13]:
import torch
from torch.autograd import backward

In [14]:
x = torch.arange(4.0,requires_grad=True)

In [15]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [16]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [17]:
x.grad == 4 * x

tensor([True, True, True, True])

In [18]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [28]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [33]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([0., 1., 4., 9.])

In [30]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])